Fix compiler error when building with FASTBuild
FASTBuild attempts to preprocess and cache element_iterator.hpp, but
the missing space between the ")" and the "const" tokens cause the
compiler to throw error C2065: 'Intervalconst': undeclared identifier